import type { Order } from '../services/db';
import { getProductionStatus } from '../constants/orderLifecycle';

export const DELIVERY_DATE_AUDIT_PREFIX = '__delivery_date_change__';

const AUTO_STATUS_COMMENT_MARKERS = [
    'تم إضافة/تحديث رابط التصميم',
    'تم رفع التصميم',
    'تم تسليم التصميم',
    'رابط التصميم',
    'تم طلب تعديل على التصميم',
];

type OrderComment = NonNullable<Order['comments']>[number];

export function isInternalDeliveryDateAuditComment(comment?: Pick<OrderComment, 'text'> | null): boolean {
    return Boolean(comment?.text?.includes(DELIVERY_DATE_AUDIT_PREFIX));
}

export function isAutoGeneratedComment(comment?: Pick<OrderComment, 'text' | 'userId'> | null): boolean {
    if (!comment?.text) return false;
    if (comment.userId === 'system' || comment.userId === 'System') return true;
    if (isInternalDeliveryDateAuditComment(comment)) return true;
    return AUTO_STATUS_COMMENT_MARKERS.some(marker => comment.text!.includes(marker));
}

export function filterVisibleOrderComments(comments?: Order['comments']): OrderComment[] {
    return (comments || []).filter(comment => !isInternalDeliveryDateAuditComment(comment));
}

export function getLatestVisibleOrderComment(comments?: Order['comments']): OrderComment | null {
    const visibleComments = filterVisibleOrderComments(comments);
    return visibleComments.length > 0 ? visibleComments[visibleComments.length - 1] : null;
}

export function getOrderCardDisplayDate(order: Pick<Order, 'status' | 'deliveryDate' | 'actualDeliveryDate'>) {
    const isDeliveredLike = getProductionStatus(order) === 'delivered';

    if (isDeliveredLike) {
        return {
            label: 'تاريخ التسليم الفعلي',
            date: order.actualDeliveryDate || order.deliveryDate || '',
        };
    }

    return {
        label: 'تاريخ التسليم المطلوب',
        date: order.deliveryDate || '',
    };
}